In [1]:
import socket
socket.gethostname()

'Rajaths-Air.lan'

In [1]:
#importing libraries for different models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier

#others
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
#data splitting
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [6]:
lr = LogisticRegression(max_iter=10000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9722222222222222

In [7]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9916666666666667

In [8]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.975

### Using K-fold

In [9]:
from sklearn.model_selection import KFold
kf =KFold(n_splits=3)                       #numb of folds
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
# for demonstration purpose
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [11]:
#defining prection method that return scores
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [12]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [14]:
print(scores_logistic)
print(scores_svm)
print(scores_rf)

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]
[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]
[0.9131886477462438, 0.9398998330550918, 0.9181969949916527]


#### Using cross_val_score function from sklearn

In [15]:
from sklearn.model_selection import cross_val_score

In [16]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [17]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [18]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92988314, 0.94824708, 0.92988314])

Later perform parameter tuning